<?php
echo "<html>\n";
echo "<head>\n";
echo "<meta http-equiv=Content-Type content=\"text/html; charset=gb2312\">\n";
echo "<meta name=Generator content=\"Microsoft Word 12 (filtered)\">\n";
echo "<style>\n";
echo "!--\n";
echo "/* Font Definitions */\n";
echo "@font-face\n";
echo "{font-family:Wingdings;\n";
echo "panose-1:5 0 0 0 0 0 0 0 0 0;}\n";
echo "font-face\n";
echo "{font-family:宋体;\n";
echo "panose-1:2 1 6 0 3 1 1 1 1 1;}\n";
echo "font-face\n";
echo "{font-family:\"Cambria Math\";\n";
echo "panose-1:2 4 5 3 5 4 6 3 2 4;}\n";
echo "font-face\n";
echo "{font-family:Calibri;\n";
echo "panose-1:2 15 5 2 2 2 4 3 2 4;}\n";
echo "font-face\n";
echo "{font-family:\"\\@宋体\";\n";
echo "panose-1:2 1 6 0 3 1 1 1 1 1;}\n";
echo "/* Style Definitions */\n";
echo "p.MsoNormal, li.MsoNormal, div.MsoNormal\n";
echo "{margin:0cm;\n";
echo "margin-bottom:.0001pt;\n";
echo "text-align:justify;\n";
echo "text-justify:inter-ideograph;\n";
echo "font-size:10.5pt;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo ".MsoHeader, li.MsoHeader, div.MsoHeader\n";
echo "{margin:0cm;\n";
echo "margin-bottom:.0001pt;\n";
echo "text-align:justify;\n";
echo "text-justify:inter-ideograph;\n";
echo "layout-grid-mode:char;\n";
echo "border:none;\n";
echo "padding:0cm;\n";
echo "font-size:9.0pt;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo ".MsoFooter, li.MsoFooter, div.MsoFooter\n";
echo "{margin:0cm;\n";
echo "margin-bottom:.0001pt;\n";
echo "layout-grid-mode:char;\n";
echo "font-size:9.0pt;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo ":link, span.MsoHyperlink\n";
echo "{color:blue;\n";
echo "text-decoration:underline;}\n";
echo ":visited, span.MsoHyperlinkFollowed\n";
echo "{color:#954F72;\n";
echo "text-decoration:underline;}\n";
echo ".MsoAcetate, li.MsoAcetate, div.MsoAcetate\n";
echo "{mso-style-link:\"批注框文本 Char\";\n";
echo "margin:0cm;\n";
echo "margin-bottom:.0001pt;\n";
echo "text-align:justify;\n";
echo "text-justify:inter-ideograph;\n";
echo "font-size:9.0pt;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo ".MsoListParagraph, li.MsoListParagraph, div.MsoListParagraph\n";
echo "{margin:0cm;\n";
echo "margin-bottom:.0001pt;\n";
echo "text-align:justify;\n";
echo "text-justify:inter-ideograph;\n";
echo "text-indent:21.0pt;\n";
echo "font-size:10.5pt;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo "pan.Char\n";
echo "{mso-style-name:\"批注框文本 Char\";\n";
echo "mso-style-link:批注框文本;\n";
echo "font-family:\"Times New Roman\",\"serif\";}\n";
echo "MsoChpDefault\n";
echo "{font-size:10.0pt;}\n";
echo "/* Page Definitions */\n";
echo "@page WordSection1\n";
echo "{size:734.25pt 1040.45pt;\n";
echo "margin:72.0pt 90.0pt 72.0pt 90.0pt;\n";
echo "layout-grid:15.6pt;}\n";
echo "iv.WordSection1\n";
echo "{page:WordSection1;}\n";
echo "/* List Definitions */\n";
echo "ol\n";
echo "{margin-bottom:0cm;}\n";
echo "ul\n";
echo "{margin-bottom:0cm;}\n";
echo "div\n";
echo "{width:44%;margin:0 auto;}\n";
echo "->\n";
echo "</style>\n";
echo "</head>\n";
echo "<body lang=ZH-CN link=blue vlink=\"#954F72\" style='text-justify-trim:punctuation'>\n";
echo "<div class=WordSection1 style='layout-grid:15.6pt'>\n";
echo "<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0 align=left\n";
echo "width=723 style='border-collapse:collapse;border:none;margin-left:6.75pt;\n";
echo "margin-right:6.75pt'>\n";
echo "<tr style='height:35.5pt'>\n";
echo " <td width=723 colspan=14 valign=top style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:35.5pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><b><span\n";
echo " style='font-size:36.0pt;font-family:宋体;color:black'>个人简历</span></b></p>\n";
echo " <p class=MsoNormal><span lang=EN-US style='background:silver'>&nbsp;</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:25.45pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;background:#00B0F0;padding:0cm 5.4pt 0cm 5.4pt;height:25.45pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:15.0pt;font-family:宋体;color:white'>基本信息</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:31.2pt'>\n";
echo " <td width=116 colspan=2 style='width:87.35pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>姓名</span></p>\n";
echo " </td>\n";
echo " <td width=122 colspan=3 style='width:91.4pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>殷少航</span></p>\n";
echo " </td>\n";
echo " <td width=142 colspan=3 style='width:106.6pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>性别</span></p>\n";
echo " </td>\n";
echo " <td width=56 colspan=2 style='width:41.8pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>男</span></p>\n";
echo " </td>\n";
echo " <td width=115 colspan=3 style='width:86.35pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>民族</span></p>\n";
echo " </td>\n";
echo " <td width=172 style='width:128.75pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>汉</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:31.2pt'>\n";
echo " <td width=116 colspan=2 style='width:87.35pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>出生年月</span></p>\n";
echo " </td>\n";
echo " <td width=122 colspan=3 style='width:91.4pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US>1993-07-07</span></p>\n";
echo " </td>\n";
echo " <td width=142 colspan=3 style='width:106.6pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>婚姻状况</span></p>\n";
echo " </td>\n";
echo " <td width=56 colspan=2 style='width:41.8pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>未婚</span></p>\n";
echo " </td>\n";
echo " <td width=115 colspan=3 style='width:86.35pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>政治面貌</span></p>\n";
echo " </td>\n";
echo " <td width=172 style='width:128.75pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>群众</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:31.2pt'>\n";
echo " <td width=116 colspan=2 style='width:87.35pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>籍贯</span></p>\n";
echo " </td>\n";
echo " <td width=122 colspan=3 style='width:91.4pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>湖北</span></p>\n";
echo " </td>\n";
echo " <td width=142 colspan=3 style='width:106.6pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>现所在地</span></p>\n";
echo " </td>\n";
echo " <td width=56 colspan=2 style='width:41.8pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>七浦路</span></p>\n";
echo " </td>\n";
echo " <td width=115 colspan=3 style='width:86.35pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>健康状况</span></p>\n";
echo " </td>\n";
echo " <td width=172 style='width:128.75pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:31.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>良</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:21.95pt'>\n";
echo " <td width=116 colspan=2 style='width:87.35pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:21.95pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>技能特长</span></p>\n";
echo " </td>\n";
echo " <td width=607 colspan=12 style='width:454.9pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:21.95pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:12.0pt;font-family:宋体;color:#2E74B5'>技能<span lang=EN-US>/</span>语言：\n";
echo " <span lang=EN-US>c</span>语言<span lang=EN-US>&nbsp;</span>良好<span lang=EN-US>&nbsp;</span>，<span\n";
echo " lang=EN-US>&nbsp; </span>嵌入式<span lang=EN-US>&nbsp;</span>良好，<span\n";
echo " lang=EN-US>&nbsp; Linux&nbsp;</span>一般，<span lang=EN-US>&nbsp; ccnp&nbsp;</span>熟练</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:24.35pt'>\n";
echo " <td width=116 colspan=2 style='width:87.35pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:24.35pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>求职意向</span></p>\n";
echo " </td>\n";
echo " <td width=607 colspan=12 style='width:454.9pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:24.35pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>网络工程师</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>/</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>初级运维工程师</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:12.85pt'>\n";
echo " <td width=723 colspan=14 valign=top style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:12.85pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#333333'>&nbsp;</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:26.2pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;background:#00B0F0;padding:0cm 5.4pt 0cm 5.4pt;height:26.2pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:15.0pt;font-family:宋体;color:white'>联系方式</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:26.0pt'>\n";
echo " <td width=153 colspan=3 style='width:115.0pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:26.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>联系电话</span></p>\n";
echo " </td>\n";
echo " <td width=163 colspan=3 style='width:122.25pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:26.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>13995666024</span></p>\n";
echo " </td>\n";
echo " <td width=120 colspan=4 style='width:89.9pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:26.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>电子邮件</span></p>\n";
echo " </td>\n";
echo " <td width=287 colspan=4 style='width:215.1pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:26.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>yh5280268@126.com</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:19.0pt'>\n";
echo " <td width=153 colspan=3 style='width:115.0pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:19.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>原住地址</span></p>\n";
echo " </td>\n";
echo " <td width=283 colspan=7 style='width:212.15pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:19.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>湖北孝感安陆市南城办事处山坡村</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>2</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>组</span></p>\n";
echo " </td>\n";
echo " <td width=81 style='width:60.85pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:19.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>邮政编码</span></p>\n";
echo " </td>\n";
echo " <td width=206 colspan=3 style='width:154.25pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:19.0pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>432600</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:28.25pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;background:#00B0F0;padding:0cm 5.4pt 0cm 5.4pt;height:28.25pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:16.0pt;font-family:宋体;color:white'>教育培训经历</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:23.4pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>时间</span></p>\n";
echo " </td>\n";
echo " <td width=158 colspan=3 style='width:118.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>学校</span></p>\n";
echo " </td>\n";
echo " <td width=80 colspan=2 style='width:60.0pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>学历</span></p>\n";
echo " </td>\n";
echo " <td width=123 colspan=3 style='width:91.9pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>专业</span></p>\n";
echo " </td>\n";
echo " <td width=192 colspan=2 style='width:144.1pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>补充描述</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:23.4pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>2006-2009</span></p>\n";
echo " </td>\n";
echo " <td width=158 colspan=3 style='width:118.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>安陆南城初中</span></p>\n";
echo " </td>\n";
echo " <td width=80 colspan=2 style='width:60.0pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>&nbsp;</span></p>\n";
echo " </td>\n";
echo " <td width=123 colspan=3 style='width:91.9pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>&nbsp;</span></p>\n";
echo " </td>\n";
echo " <td width=192 colspan=2 style='width:144.1pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='color:#2E74B5'>&nbsp;</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:23.4pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>2009.6-2010.5</span></p>\n";
echo " </td>\n";
echo " <td width=158 colspan=3 style='width:118.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>安陆市职业技术学校</span></p>\n";
echo " </td>\n";
echo " <td width=80 colspan=2 style='width:60.0pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>中专</span></p>\n";
echo " </td>\n";
echo " <td width=123 colspan=3 style='width:91.9pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>信息技术</span></p>\n";
echo " </td>\n";
echo " <td width=192 colspan=2 style='width:144.1pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>毕业</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:23.4pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>2017.6-2019.5</span></p>\n";
echo " </td>\n";
echo " <td width=158 colspan=3 style='width:118.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>上海交通大学徐汇校区</span></p>\n";
echo " </td>\n";
echo " <td width=80 colspan=2 style='width:60.0pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>大专</span></p>\n";
echo " </td>\n";
echo " <td width=123 colspan=3 style='width:91.9pt;border-top:none;border-left:none;\n";
echo " border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>计算机信息技术</span></p>\n";
echo " </td>\n";
echo " <td width=192 colspan=2 style='width:144.1pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:23.4pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体;color:#2E74B5'>成人大专</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:19.0pt'>\n";
echo " <td width=723 colspan=14 valign=top style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:19.0pt'>\n";
echo " <p class=MsoListParagraph style='margin-left:21.0pt;text-indent:0cm'><span\n";
echo " lang=EN-US>&nbsp;</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:28.25pt'>\n";
echo " <td width=723 colspan=14 valign=top style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;background:#00B0F0;padding:0cm 5.4pt 0cm 5.4pt;height:28.25pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:16.0pt;font-family:宋体;color:white;background:#00B0F0'>工作经历</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:21.1pt'>\n";
echo " <td width=170 colspan=4 valign=top style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:21.1pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>时间</span></p>\n";
echo " </td>\n";
echo " <td width=553 colspan=10 valign=top style='width:414.5pt;border-top:none;\n";
echo " border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:21.1pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-family:宋体'>单位名称</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:47.55pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'>2012.05</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy'>—</span><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'> 2014.06</span></p>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US>&nbsp;</span></p>\n";
echo " </td>\n";
echo " <td width=553 colspan=10 style='width:414.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>上海悠唐网络科技有限公司</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>&lt;</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>主要负责思科</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>AC&lt;6605&gt;\n";
echo " </span><span style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>华为防火墙</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>&lt;2150&gt;&lt;9306&gt;</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:#2E74B5'>以及部分服务器相关业务</span><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:#2E74B5'>&gt;</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:47.55pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'>2014.06</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy'>—</span><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'> 2016.06</span></p>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US>&nbsp;</span></p>\n";
echo " </td>\n";
echo " <td width=553 colspan=10 style='width:414.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='margin-bottom:.75pt;text-align:center'><b><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy;background:white'>瓦格科技</span></b><b><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:navy;\n";
echo " background:white'>&lt;</span></b><b><span style='font-size:11.0pt;font-family:\n";
echo " 宋体;color:navy;background:white'>主要负责思科</span></b><b><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy;background:white'>&lt;3750&gt;&lt;2960&gt;&lt;netflow&gt;</span></b><b><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy;background:white'>以及熟悉</span></b><b><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:navy;\n";
echo " background:white'>Linux apache tomcat nginx mysql DB2 oracle </span></b><b><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy;background:white'>熟悉</span></b><b><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:\"Courier New\";color:navy;\n";
echo " background:white'>vmware Vsphere</span></b><b><span style='font-size:11.0pt;\n";
echo " font-family:宋体;color:navy;background:white'>集群</span></b><b><span\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy;background:white'>\n";
echo " </span></b><span lang=EN-US style='font-size:13.5pt;font-family:\"Arial\",\"sans-serif\";\n";
echo " color:#333333;background:white'>&nbsp;</span><b><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy;background:white'>&gt;</span></b></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:47.55pt'>\n";
echo " <td width=170 colspan=4 style='width:127.75pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'>2016.06</span><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy'>—</span><span lang=EN-US\n";
echo " style='font-size:11.0pt;font-family:\"Courier New\";color:navy'> 2018.01</span></p>\n";
echo " </td>\n";
echo " <td width=553 colspan=10 style='width:414.5pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='margin-bottom:.75pt;text-align:center'><b><span\n";
echo " style='font-size:11.0pt;font-family:宋体;color:navy;background:white'>兆恒伟业香港<span\n";
echo " lang=EN-US>IDC</span></span></b><b><span lang=EN-US style='font-size:11.0pt;\n";
echo " font-family:\"Courier New\";color:navy;background:white'>&lt;</span></b><b><span\n";
echo " lang=EN-US style='font-size:11.0pt;font-family:宋体;color:navy;background:white'>\n";
echo " </span></b><b><span style='font-size:11.0pt;font-family:宋体;color:navy;\n";
echo " background:white'>熟悉大型<span lang=EN-US>idc</span>网络架构拓扑 以及相关<span lang=EN-US>bgp\n";
echo " mpls</span>协议 更新以及修复网络拓扑（安全）<span lang=EN-US>&nbsp; </span>培训网络层</span></b><span\n";
echo " lang=EN-US style='font-family:\"Arial\",\"sans-serif\";color:#2E74B5;background:\n";
echo " white'>IS-IS · IPsec&nbsp;</span><span lang=EN-US><a\n";
echo " href=\"http://baike.baidu.com/view/239605.htm\"\n";
echo " target=\"http://h-ylove.me/_blank\"><span lang=EN-US style='font-family:宋体;\n";
echo " color:#2E74B5;background:white'><span lang=EN-US>传输层</span></span></a></span><span\n";
echo " lang=EN-US style='font-family:\"Calibri\",\"sans-serif\";color:#2E74B5'> </span><span\n";
echo " lang=EN-US style='font-family:\"Arial\",\"sans-serif\";color:#2E74B5;background:\n";
echo " white'>OSPF TCP · UDP · TLS &nbsp;</span><span lang=EN-US><a\n";
echo " href=\"http://baike.baidu.com/view/239619.htm\"\n";
echo " target=\"http://h-ylove.me/_blank\"><span lang=EN-US style='font-family:宋体;\n";
echo " color:#2E74B5;background:white'><span lang=EN-US>应用层</span></span></a></span><span\n";
echo " class=MsoHyperlink><span lang=EN-US style='font-family:\"Arial\",\"sans-serif\";\n";
echo " color:#2E74B5;background:white'> </span></span><span lang=EN-US\n";
echo " style='font-family:\"Arial\",\"sans-serif\";color:#2E74B5;background:white'>&nbsp;·\n";
echo " IBGP ·BGP HTTP·RIP&nbsp; </span><span style='font-family:宋体;color:#2E74B5;\n";
echo " background:white'>实际运用以及故障排查</span><span lang=EN-US style='font-family:\"Arial\",\"sans-serif\";\n";
echo " color:#2E74B5;background:white'>&nbsp;&nbsp; wireshark</span><span\n";
echo " style='font-family:宋体;color:#2E74B5;background:white'>数据包分析等</span><span\n";
echo " style='font-size:13.5pt;font-family:\"Arial\",\"sans-serif\";color:#2E74B5;\n";
echo " background:white'> </span><b><span lang=EN-US style='font-size:11.0pt;\n";
echo " font-family:\"Courier New\";color:#2E74B5;background:white'>&gt;</span></b></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:27.55pt'>\n";
echo " <td width=723 colspan=14 valign=top style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;background:#00B0F0;padding:0cm 5.4pt 0cm 5.4pt;height:27.55pt'>\n";
echo " <p class=MsoNormal align=center style='margin-bottom:.75pt;text-align:center'><span\n";
echo " style='font-size:15.0pt;font-family:宋体;color:white'>项目经验</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:47.55pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US>2013/1-2013/7&nbsp;&nbsp;&nbsp;\n";
echo " </span><span style='font-family:宋体'>国内某大型银行省级更新实施</span><span lang=EN-US>&nbsp;\n";
echo " </span><span style='font-family:宋体'>全省银行数据数通以及相关设备跟新换代</span> <span\n";
echo " style='font-family:宋体'>内网数据架构以及中</span><span lang=EN-US>&nbsp; </span><span\n";
echo " style='font-family:宋体'>心机房的相关灾备</span> <span style='font-family:宋体'>广域网通讯安全架构设计</span><span\n";
echo " lang=EN-US>&nbsp; </span><span style='font-family:宋体'>负责全省银行网络大型出差项目负责实施上架以及调试</span>\n";
echo " <span style='font-family:宋体'>配合电信移动等运营商售配合操作</span> <span style='font-family:\n";
echo " 宋体'>保证网络的正常使用以及设备正常更新换代以及参与项目部分设计调控</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:47.55pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:47.55pt'>\n";
echo " <p class=MsoNormal align=center style='margin-bottom:.75pt;text-align:center'><span\n";
echo " lang=EN-US style='font-family:宋体'>2014/1-2014/6&nbsp;&nbsp; </span><span\n";
echo " style='font-family:宋体'>华为无线覆盖项目 已关联<span lang=EN-US>&nbsp;&nbsp; </span>企业无线覆盖\n";
echo " 使用设备<span lang=EN-US> hw2150 ac6605 </span>多个<span lang=EN-US>AP </span>无线网规 信号质</span></p>\n";
echo " <p class=MsoNormal align=center style='margin-bottom:.75pt;text-align:center'><span\n";
echo " style='font-family:宋体'>量实施检测 以及无线传输效率提升 调优 方案定制 无线漫游<span lang=EN-US> ac</span>核心优化\n";
echo " 熟悉无线相关数据概念</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:24.7pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:24.7pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:12.0pt;font-family:宋体'>2015/5-2016/6&nbsp; </span><span\n";
echo " style='font-size:12.0pt;font-family:宋体'>无线覆盖方案设计与企业网对接<span lang=EN-US>&nbsp;&nbsp;<img\n";
echo " border=0 width=20 height=15 id=\"图片 1\" src=\"images/image001.gif\"\n";
echo " alt=\"IMG_256\">www.1218.com</span>设备 负责上架无线安全认证设备<span lang=EN-US>&nbsp;</span>以及企业拓扑调优变更<span\n";
echo " lang=EN-US>&nbsp;</span>调优无线覆盖质量和覆盖信号强度<span lang=EN-US>&nbsp;</span>对接短信认证<span\n";
echo " lang=EN-US>&nbsp;</span>和认证失效管理<span lang=EN-US>&nbsp;</span>熟悉<span\n";
echo " lang=EN-US>linux</span>配置 管理。</span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:24.7pt'>\n";
echo " <td width=723 colspan=14 style='width:542.25pt;border:solid windowtext 1.0pt;\n";
echo " border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:24.7pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span lang=EN-US\n";
echo " style='font-size:12.0pt;font-family:宋体'>2017/10-2018/04&nbsp; </span><span\n";
echo " style='font-size:12.0pt;font-family:宋体'>企业无线覆盖方案设计及上架<span lang=EN-US>&nbsp;</span>调优无线覆盖质量和覆盖信号强度<span\n";
echo " lang=EN-US>&nbsp;</span>无线微信认证对接 以及用户需求的及时处理和反馈<span lang=EN-US>&lt;</span>无线有线覆盖方案<span\n";
echo " lang=EN-US>&gt;</span></span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr style='height:24.7pt'>\n";
echo " <td width=57 style='width:43.1pt;border:solid windowtext 1.0pt;border-top:\n";
echo " none;padding:0cm 5.4pt 0cm 5.4pt;height:24.7pt'>\n";
echo " <p class=MsoNormal align=center style='text-align:center'><span\n";
echo " style='font-size:12.0pt;font-family:宋体'>其他</span></p>\n";
echo " </td>\n";
echo " <td width=666 colspan=13 style='width:499.15pt;border-top:none;border-left:\n";
echo " none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n";
echo " padding:0cm 5.4pt 0cm 5.4pt;height:24.7pt'>\n";
echo " <p class=MsoNormal align=left style='text-align:left'><span style='font-size:\n";
echo " 12.0pt;font-family:宋体'>个人网站<span lang=EN-US>:www.drin.me</span></span></p>\n";
echo " <p class=MsoNormal align=left style='text-align:left'><span style='font-size:\n";
echo " 12.0pt;font-family:宋体'>个人在线简历：<span lang=EN-US>www.drin.me/yinshaohang.php</span></span></p>\n";
echo " </td>\n";
echo "</tr>\n";
echo "<tr height=0>\n";
echo " <td width=57 style='border:none'></td>\n";
echo " <td width=59 style='border:none'></td>\n";
echo " <td width=37 style='border:none'></td>\n";
echo " <td width=17 style='border:none'></td>\n";
echo " <td width=68 style='border:none'></td>\n";
echo " <td width=78 style='border:none'></td>\n";
echo " <td width=12 style='border:none'></td>\n";
echo " <td width=52 style='border:none'></td>\n";
echo " <td width=28 style='border:none'></td>\n";
echo " <td width=28 style='border:none'></td>\n";
echo " <td width=81 style='border:none'></td>\n";
echo " <td width=14 style='border:none'></td>\n";
echo " <td width=20 style='border:none'></td>\n";
echo " <td width=172 style='border:none'></td>\n";
echo "</tr>\n";
echo "</table>\n";
echo "<p class=MsoNormal><span lang=EN-US>&nbsp;</span></p>\n";
echo "</div>\n";
echo "</body>\n";
echo "</html>\n";
?>
